before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y gcc-arm-linux-gnueabi

os: linux
dist: trusty
language: c
script:
  - cmake ./CMakeLists.txt
  - for PROJECT in ./*/CMakeLists.txt; do
      cd ${PROJECT%*/*} && make && cd ../;
    done