os: linux
dist: trusty
sudo: required

services:
  - docker

script:
  - ./docker make
  - ./docker package

deploy:
  provider: releases
  prerelease: true
  api_key: ${GH_TOKEN}
  file_glob: true
  file: target/*
  skip_cleanup: true
  on:
    tags: true
    branch: master